### ISSUE TITLE
Include folk: Fran Iglesias

### ISSUE THREAD

**Issue by dcarral** [keep-calm-and-nice-software/happy-learning#13]
- https://twitter.com/talkingbit1, @franiglesias
- Author @ [La guía del refactor cotidiano](https://leanpub.com/refactorcotidiano), [A blog about programming, mainly PHP, and maybe other things](https://franiglesias.github.io/), [Testing y TDD para PHP](https://leanpub.com/testingytddparaphp), etc.
- Did I hear something about a ˝Fran Iglesias fan club˝ during session 3? 😆
- Thank you very much @Jonatanmdez… what an awesome discovery!

**Comment by Jonatanmdez** [comment]
Created PR https://github.com/keep-calm-and-nice-software/happy-learning/pull/25

**Comment by dcarral** [comment]
Closing this as #25 has been just merged ;)
