### ISSUE TITLE
Include folk: Dragan Stepanović

### ISSUE THREAD

**Issue by dcarral** [keep-calm-and-nice-software/happy-learning#19]
- https://twitter.com/d_stepanovic, @dragan-stepanovic
- Appeared during free-flowing ˝learn or code˝ block @ session 3. Doing mob programming with his colleagues @ Pakistan! :-)
- After ˝messaging˝ spontaneously appeared during session 2, and without knowing anything about KC&NS, Dragan recommended me to check out ˝Why People…˝ . That talk is a classic (and top) resource to properly understand the concept of ˝messaging˝ in Object-Oriented programming (see https://github.com/keep-calm-and-nice-software/happy-learning/issues/11)
- Fwiw, Dragan, besides being a great guy, is one of the strongest software developers I've ever met. Often puzzled how much he knows… and how good he transmits that information. Completely worth following him 👍

**Comment by dcarral** [comment]
Shared by Dragan today, and perfectly blending KC&NS sessions 2 & 3: ["Tell, don't ask" kata](https://github.com/gabrieletondi/tell-dont-ask-kata), by @gabrieletondi.

**Comment by Jonatanmdez** [comment]
@dcarral very interesting that kata, with focus in that principle :D
